server:
  port: 11667
spring:
  datasource:
    url: jdbc:mysql://106.126.9.3:3306/water?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Tianya0820666..
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: 106.126.9.3
#    password: Tianya0820666..
#    port: 6379
#    database: 0
#    connect-timeout: 60s

#      mybatisPlus配置
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag #删除标志
      logic-delete-value: 1 #表示删除
      logic-not-delete-value: 0 #表示未删除
      id-type: auto #主键自增长

  #      配置映射文件的位置
  mapper-locations: classpath*:com/jie/mapper/*.xml
